name: Approve or Deny Marketplace Action Request

on:
  issue_comment:
    types: [created]

jobs:
  approve-or-deny-request:
    runs-on: self-hosted
    steps:
    - name: Get JSON Data out of Issue Request
      uses: peter-murray/issue-body-parser-action@v1
      id: issue_body_parser_request
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_id: ${{ github.event.issue.number }}
        payload_marker: request
    - name: Check out scripts
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Install dependencies
      run: |
        cd .github/scripts
        npm install
    - name: Dump github context
      run: echo '${{ toJSON(github) }}'
    - name: Approve or deny request
      uses: actions/github-script@main
      with:
        debug: true
        script: |
          const options = { token: '${{ secrets.TOKEN }}', baseUrl: '${{ github.api_url }}'};
          const payload = ${{ steps.issue_body_parser_request.outputs.payload }}
          await require('./.github/scripts/approve-or-deny-request.js')({github, context, payload, options});
