name: Approve or Deny Marketplace Action Request

on:
  issue_comment:
    types: [created]

jobs:
  approve-or-deny-request:
    runs-on: self-hosted
    steps:
    - name: Get JSON Data out of Issue Request
      uses: peter-murray/issue-body-parser-action@v1
      id: issue_body_parser_request
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_id: ${{ github.event.issue.number }}
        payload_marker: request
    - name: Check out scripts
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Install dependencies
      run: |
        cd .github/scripts
        npm install
    - name: Lookup the latest release of ${{ fromJson(steps.issue_body_parser_request.outputs.payload).owner }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}
      id: get_version
      run: |
        if [ '${{ fromJson(steps.issue_body_parser_request.outputs.payload).version }}' == 'latest' ]; then
          export VERSION=`curl https://api.github.com/repos/${{ fromJson(steps.issue_body_parser_request.outputs.payload).owner }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}/releases/latest | jq -r .name`
        else
          export VERSION=${{ fromJson(steps.issue_body_parser_request.outputs.payload).version }}
        fi
        echo "VERSION: $VERSION"
        echo "::set-output name=version::$VERSION"
    - name: Approve or deny request
      uses: actions/github-script@main
      with:
        debug: true
        script: |
          const options = { token: '${{ secrets.TOKEN }}', adminOpsOrg: '${{ secrets.ADMIN_OPS_ORG }}', actionsApprovedOrg: '${{ secrets.ACTIONS_APPROVED_ORG }}', actionsApproverTeam: '${{ secrets.ACTIONS_APPROVERS_TEAM }}', baseUrl: '${{ github.api_url }}', version: '${{ steps.get_version.outputs.version }}' };
          const payload = ${{ steps.issue_body_parser_request.outputs.payload }}
          await require('./.github/scripts/approve-or-deny-request.js')({github, context, payload, options});
