name: Approve or Deny Marketplace Action Request

on:
  issue_comment:
    types: [created]

jobs:
  approve-or-deny-request:
    runs-on: self-hosted
    steps:
    - name: Check out scripts
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Install dependencies
      run: |
        cd .github/scripts
        npm install
    - name: Dump github context
      run: echo '${{ toJSON(github) }}'
    - name: Approve or deny request
      uses: actions/github-script@main
      with:
        debug: true
        script: |
          const options = { token: '${{ secrets.TOKEN }}', baseUrl: '${{ github.api_url }}' };
          await require('./.github/scripts/approve-or-deny-request.js')({github, context, options});
