name: Initialize Marketplace Action Request

on:
  issues:
    types: [opened]

jobs:
  initialize-request:
    runs-on: self-hosted
    steps:
    - name: Get JSON Data out of Issue Request
      uses: peter-murray/issue-body-parser-action@v1
      id: issue_body_parser_request
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_id: ${{ github.event.issue.number }}
        payload_marker: request
    - name: Check out scripts
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Install dependencies
      run: |
        cd .github/scripts
        npm install
    - name: Dump steps context
      run: echo '${{ toJSON(steps) }}'
    - name: Lookup the latest release of ${{ fromJson(steps.issue_body_parser_request.outputs.payload).owner }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}
      id: lookup_latest_release
      run: |
        export LATEST=`curl https://api.github.com/repos/${{ fromJson(steps.issue_body_parser_request.outputs.payload).owner }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}/releases/latest | jq -r .name`
        echo "LATEST RELEASE: $LATEST"
        echo "::set-output name=latest_release::$LATEST"
    - name: Create the repo ${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}_${{ steps.lookup_latest_release.outputs.latest_release }} on GitHub Enterprise Server
      uses: actions/github-script@main
      with:
        debug: true
        script: |
          const options = { token: '${{ secrets.TOKEN }}', actionsApprovedOrg: '${{ secrets.ACTIONS_APPROVED_ORG }}', baseUrl: '${{ github.api_url }}', latestRelease: '${{ steps.lookup_latest_release.outputs.latest_release }}' };
          const payload = ${{ steps.issue_body_parser_request.outputs.payload }}
          await require('./.github/scripts/initialize-request.js')({github, context, payload, options});
    - name: Check out requested action repo ${{ fromJson(steps.issue_body_parser_request.outputs.payload).owner }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}_${{ steps.lookup_latest_release.outputs.latest_release }}
      run: |
        git clone https://github.com/'${{ fromJson(steps.issue_body_parser_request.outputs.payload).owner }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}' requested-action
    - name: Show the directory
      run: ls -l requested-action
    - name: Push requested action to private repo in $ACTIONS_APPROVED_ORG org on GitHub Enterprise Server
      run: |
        cd requested-action
        git config user.email '${{ secrets.GITHUB_EMAIL }}'
        git config user.name '${{ secrets.GITHUB_USERNAME }}'
        if git checkout main; then
          git branch -m main-old
        fi
        git checkout ${{ steps.lookup_latest_release.outputs.latest_release }}
        git switch -c ${{ steps.lookup_latest_release.outputs.latest_release }}-branch
        git branch -m main
        git remote add origin2 ${{ github.server_url }}/${{ secrets.ACTIONS_APPROVED_ORG }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}_${{ steps.lookup_latest_release.outputs.latest_release }}.git
        git push -u origin2 main
        git push -u origin2 ${{ steps.lookup_latest_release.outputs.latest_release }}
        