name: Initialize Request

on:
  issues:
    types: [opened, edited]

jobs:
  initialize-request:
    runs-on: self-hosted
    steps:
    - name: Check out scripts
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        check-latest: true
    - name: Install dependencies
      run: |
        cd .github/scripts
        npm install

    - name: Get JSON Data out of Issue Request
      uses: peter-murray/issue-body-parser-action@v1
      id: issue_body_parser_request
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        issue_id: ${{ github.event.issue.number }}
        payload_marker: request
    - name: Dump steps context
      run: echo '${{ toJSON(steps) }}'
    - name: Check out requested action repo
      run: |
        git clone https://github.com/'${{ fromJson(steps.issue_body_parser_request.outputs.payload).owner }}/${{ fromJson(steps.issue_body_parser_request.outputs.payload).repo }}' requested-action
    - name: Show the directory
      run: ls -l requested-action
    - name: Initialize GitHub Marketplace Action Request
      uses: actions/github-script@main
      with:
        debug: true
        script: |
          const options = { token: '${{ secrets.TOKEN }}', baseUrl: '${{ github.api_url }}' };
          const payload = ${{ steps.issue_body_parser_request.outputs.payload }}
          await require('./.github/scripts/initialize-request.js')({github, context, payload, options});